name: cicd

on:
  push:
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      DOTNET_NOLOGO: true
    defaults:
      run:
        working-directory: src
    steps:
    - uses: actions/checkout@v2
    - uses: olegtarasov/get-tag@v2.1
      id: tag
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - run: echo "::remove-matcher owner=csc::"
    - uses: reviewdog/action-setup@v1
    - run: dotnet --info
    - run: dotnet restore
    - run: dotnet build -c Release --no-restore | tee dotnet.buildlog
    - uses: SamhammerAG/dotnet-reviewdog-action@v1
      with:
        workdir: src
        reporter: github-check
        line_exclude_regex: ".*(warning|error) CS0618:.*"
    - run: dotnet pack -c Release -p:Version=${{ steps.tag.outputs.tag || '1.0' }} --output nuget-packages
    - if: startsWith(github.ref, 'refs/tags/') 
      run: cd nuget-packages; dotnet nuget push "**/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate --source https://api.nuget.org/v3/index.json
